# conda env create --file environment.yml
# mamba env create --file environment.yml
name: regresion_lineal
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - keras
  - lightgbm
  - matplotlib==3.7.3
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - plotly
  - pyjanitor
  - pylint
  - pyprojroot
  - pyspark
  - scikit-learn
  - seaborn
  - statsmodels
  - tensorflow
  - pip
  - python=3.9
  - python-dotenv
  - session-info
  - pyreadr
  - upsetplot
  - fancyimpute
  - scipy
pip:
  - setuptools==58
  - regressors
